### ISSUE TITLE
URLs to catalogs or other child resources result in 404 errors

### ISSUE THREAD

**Issue by louis-vinchon** [FAIRDataTeam/FAIRDataPoint-client#91]
When I create a new catalog for my FAIR Data point instance, and click on it from the home page, the application "navigates" to `http://example-host.com/catalog/<uuid>` where I can see the catalog details and its child resources.

However if I try to copy and paste this URL in an other tab it results in a 404 error:
`404 | The requested path could not be found`.

This is annoying because you can't direct people to a specific resource on the FDP Client, it forces them to use the search bar or manually navigate the resources tree.

**Comment by janslifka** [comment]
This is probably some kind of issue with the deployment or configuration as the feature you describe works. You can see, for example, in this demonstration FDP that you can directly open a specific resource: https://app.fairdatapoint.org/dataset/764fc18f-9b8d-4e1f-857f-b12b194e048f
